language: node_js
node_js:
  - '8.9.0'
  - '4.4.6'
install:
  - npm install
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 63790
script:
  - npm run test
branches:
  only:
  - master